# Request
# Set the respective flags according to the required function for the service
# node to handle. This service will maintain the state of the formation
# parameters to provide an interface for updating the graph as and when required.

########################################
# FLAGS
########################################
uint8 REQUESTING_PARAMS 
uint8 UPDATING_ADJACENCY_MATRIX

########################################
# Messages
########################################
std_msgs/Float64MultiArray A_

---
# Response
std_msgs/Float64MultiArray A_
std_msgs/Float64MultiArray L_
std_msgs/Float64MultiArray D_out
std_msgs/Float64MultiArray D_in
bool success